import CryptoKit
import Darwin
import Foundation

nonisolated enum KnownPeopleLocalStoreSnapshotFailure: Error, Equatable {
    case identityAssignmentRequired
    case identityAlreadyAssigned, orphanAdmittedPackage
    case unsafeRoot, unsafeFile, unsupportedRootEntry, tombstonesPresent, invalidPerson
    case invalidStateBinding, missingReferencedThumbnail(String), unreferencedThumbnail(String)
    case changedDuringCapture, sizeLimit, io
}

nonisolated struct KnownPeopleLocalStoreInventoryToken: Equatable, Sendable {
    struct File: Equatable, Sendable { let byteCount: Int; let sha256: String }
    let device: Int32
    let inode: UInt64
    let directories: Set<String>
    let files: [String: File]
}

nonisolated struct KnownPeopleLocalStoreSnapshotCapture: Sendable {
    let snapshot: KnownPeoplePackageSnapshot
    let inventory: KnownPeopleLocalStoreInventoryToken
    let reusedAdmittedBytes: Bool
    let managedInventorySHA256: String
}

nonisolated struct KnownPeopleLocalStoreSnapshotAccess: Sendable {
    /// Root descriptor is open; its original lexical path has not yet been rechecked.
    var afterRootOpen: @Sendable () throws -> Void = {}
    /// A deterministic race/cancellation boundary after capture and before final source validation.
    var beforeFinalValidation: @Sendable () throws -> Void = {}
}

/// Strict, read-only export admission. It does not use KnownPeopleService.loadDatabase(),
/// migrate old stores, clear tombstones, infer model provenance, or assign library identity.
/// Callers must keep the local routing/owner boundary stable while this awaited capture runs.
actor KnownPeopleLocalStoreSnapshotBuilder {
    private let access: KnownPeopleLocalStoreSnapshotAccess
    init(access: KnownPeopleLocalStoreSnapshotAccess = .init()) { self.access = access }

    func capture(rootURL: URL, exportedAt: String,
                 exporter: KnownPeoplePackageManifest.Exporter) async throws -> KnownPeopleLocalStoreSnapshotCapture {
        try Task.checkCancellation()
        let root = try LocalRoot(rootURL, afterOpen: access.afterRootOpen)
        let initial = try root.capture()
        let people = try Self.people(initial.files)
        _ = try KnownPeopleInterchangeEligibility.validate(people: people)
        guard let stateBytes = initial.files[KnownPeopleManagedStoreState.fileName] else {
            // A UUID generated by an exporter would fork the identity on every export.
            // Only the local-store owner may establish this durable identity transactionally.
            throw KnownPeopleLocalStoreSnapshotFailure.identityAssignmentRequired
        }
        let state = try KnownPeopleManagedStoreState.decode(stateBytes)
        let admittedFD = openat(root.fd, state.admittedPackageDirectory, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
        guard admittedFD >= 0 else { throw KnownPeopleLocalStoreSnapshotFailure.invalidStateBinding }
        defer { close(admittedFD) }
        let admitted = try await KnownPeoplePackageDirectoryReader().read(heldDirectoryDescriptor: admittedFD,
            sourceURL: root.url.appendingPathComponent(state.admittedPackageDirectory, isDirectory: true))
        let initialAdmitted = Dictionary(uniqueKeysWithValues: initial.files.compactMap { path, bytes in
            path.hasPrefix(".admitted-package/") ? (String(path.dropFirst(".admitted-package/".count)), bytes) : nil
        })
        guard admitted.files == initialAdmitted,
              KnownPeopleManagedStoreState.admittedPackageHash(initialAdmitted) == state.admittedPackageSHA256,
              admitted.manifest.libraryID == state.libraryID,
              admitted.manifest.revision == state.currentRevision,
              admitted.manifest.coreRevision == state.currentCoreRevision,
              admitted.manifest.contract == state.contract,
              try Self.admittedProjectionHash(admitted) == state.managedProjectionSHA256 else {
            throw KnownPeopleLocalStoreSnapshotFailure.invalidStateBinding
        }

        let thumbnails = try Self.thumbnails(initial.files, people: people, admitted: admitted)
        let samePeople = try Self.canonicalPeople(people) == Self.canonicalPeople(admitted.people)
        let admittedThumbnails = admitted.files.filter { $0.key.hasPrefix("thumbnails/") || $0.key.hasPrefix("embedding_thumbnails/") }
        let exactProjection = try Self.managedProjectionHash(files: initial.files, directories: initial.directories)
        let reused = exactProjection == state.managedProjectionSHA256 && samePeople && thumbnails == admittedThumbnails
        let snapshot: KnownPeoplePackageSnapshot
        if reused {
            snapshot = .init(sourceDirectoryURL: root.url, sourceDevice: root.identity.st_dev,
                sourceInode: root.identity.st_ino, manifest: admitted.manifest, payload: admitted.payload,
                editor: admitted.editor, files: admitted.files, people: admitted.people)
        } else {
            snapshot = try Self.build(people: people, thumbnails: thumbnails, libraryID: state.libraryID,
                                      root: root, exportedAt: exportedAt, exporter: exporter)
        }
        try KnownPeoplePackageSnapshotValidation.validate(snapshot)
        try access.beforeFinalValidation()
        try Task.checkCancellation()
        let final = try root.capture()
        guard final == initial else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
        try root.verifyPath()
        return .init(snapshot: snapshot, inventory: .init(device: root.identity.st_dev, inode: root.identity.st_ino,
            directories: initial.directories, files: initial.files.mapValues { .init(byteCount: $0.count, sha256: Self.hash($0)) }),
            reusedAdmittedBytes: reused, managedInventorySHA256: initial.managedInventorySHA256)
    }

    /// Read-only first-identity input. The owner must bind this capture to its managed
    /// inventory and commit through the managed replacement gateway; this never assigns state.
    func captureUntracked(rootURL: URL, libraryID: UUID, exportedAt: String,
                          exporter: KnownPeoplePackageManifest.Exporter) async throws -> KnownPeopleLocalStoreSnapshotCapture {
        try Task.checkCancellation()
        let root = try LocalRoot(rootURL, afterOpen: access.afterRootOpen)
        let initial = try root.capture()
        guard initial.files[KnownPeopleManagedStoreState.fileName] == nil else {
            throw KnownPeopleLocalStoreSnapshotFailure.identityAlreadyAssigned
        }
        guard !initial.directories.contains(".admitted-package"),
              !initial.files.keys.contains(where: { $0.hasPrefix(".admitted-package/") }) else {
            throw KnownPeopleLocalStoreSnapshotFailure.orphanAdmittedPackage
        }
        let people = try Self.people(initial.files)
        _ = try KnownPeopleInterchangeEligibility.validate(people: people)
        let thumbnails = try Self.thumbnails(initial.files, people: people, admitted: nil)
        let snapshot = try Self.build(people: people, thumbnails: thumbnails, libraryID: libraryID,
                                      root: root, exportedAt: exportedAt, exporter: exporter)
        try KnownPeoplePackageSnapshotValidation.validate(snapshot)
        try access.beforeFinalValidation()
        try Task.checkCancellation()
        guard try root.capture() == initial else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
        try root.verifyPath()
        return .init(snapshot: snapshot, inventory: .init(device: root.identity.st_dev, inode: root.identity.st_ino,
            directories: initial.directories, files: initial.files.mapValues { .init(byteCount: $0.count, sha256: Self.hash($0)) }),
            reusedAdmittedBytes: false, managedInventorySHA256: initial.managedInventorySHA256)
    }

    private static func people(_ files: [String: Data]) throws -> [KnownPerson] {
        var output: [KnownPerson] = [], ids: Set<UUID> = []
        for (path, bytes) in files.sorted(by: { $0.key < $1.key }) where path.hasPrefix("people/") {
            if path.hasSuffix(".deleted") { throw KnownPeopleLocalStoreSnapshotFailure.tombstonesPresent }
            let name = String(path.dropFirst("people/".count))
            guard let id = localID(name, suffix: ".json"), ids.insert(id).inserted else { throw KnownPeopleLocalStoreSnapshotFailure.invalidPerson }
            try KnownPeoplePackageManifest.validateJSONStructure(bytes)
            guard let object = try JSONSerialization.jsonObject(with: bytes) as? [String: Any] else { throw KnownPeopleLocalStoreSnapshotFailure.invalidPerson }
            try keys(object, required: ["id", "name", "embeddings", "createdAt", "updatedAt"], optional: ["role", "notes", "representativeThumbnailID"])
            guard let examples = object["embeddings"] as? [[String: Any]] else { throw KnownPeopleLocalStoreSnapshotFailure.invalidPerson }
            for example in examples {
                try keys(example, required: ["id", "featurePrintData", "addedAt"], optional: ["sourceDescription", "recognitionMode", "provenance"])
                if let provenance = example["provenance"] as? [String: Any] {
                    try keys(provenance, required: ["embeddingSpaceVersion", "componentID", "modelID", "preprocessingRevision", "vectorEncoding", "dimension", "l2Normalized"])
                }
            }
            let person = try JSONDecoder().decode(KnownPerson.self, from: bytes)
            guard person.id == id else { throw KnownPeopleLocalStoreSnapshotFailure.invalidPerson }
            output.append(person)
        }
        return output.sorted { $0.id.uuidString < $1.id.uuidString }
    }

    private static func thumbnails(_ files: [String: Data], people: [KnownPerson],
                                   admitted: KnownPeoplePackageSnapshot?) throws -> [String: Data] {
        let personIDs = Set(people.map(\.id)), exampleIDs = Set(people.flatMap { $0.embeddings.map(\.id) })
        var result: [String: Data] = [:]
        for (path, bytes) in files {
            let prefix: String
            let ids: Set<UUID>
            if path.hasPrefix("thumbnails/") { prefix = "thumbnails/"; ids = personIDs }
            else if path.hasPrefix("embedding_thumbnails/") { prefix = "embedding_thumbnails/"; ids = exampleIDs }
            else { continue }
            guard let id = localID(String(path.dropFirst(prefix.count)), suffix: ".jpg"), ids.contains(id) else {
                throw KnownPeopleLocalStoreSnapshotFailure.unreferencedThumbnail(path)
            }
            let canonical = prefix + id.uuidString.lowercased() + ".jpg"
            guard result.updateValue(bytes, forKey: canonical) == nil else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeFile }
        }
        // Package paths, unlike representativeThumbnailID (an example selection), are actual
        // file references. Preserve the distinction: the shared golden editor has a selected
        // representative example with no thumbnail, which is valid schema-2 metadata.
        for person in admitted?.payload.people ?? [] where personIDs.contains(person.id) {
            if let path = person.thumbnailPath, result[path] == nil {
                throw KnownPeopleLocalStoreSnapshotFailure.missingReferencedThumbnail(path)
            }
            for example in person.examples where exampleIDs.contains(example.id) {
                if let path = example.thumbnailPath, result[path] == nil {
                    throw KnownPeopleLocalStoreSnapshotFailure.missingReferencedThumbnail(path)
                }
            }
        }
        return result
    }

    private static func build(people: [KnownPerson], thumbnails: [String: Data], libraryID: UUID,
                              root: LocalRoot, exportedAt: String,
                              exporter: KnownPeoplePackageManifest.Exporter) throws -> KnownPeoplePackageSnapshot {
        var files = thumbnails, corePeople: [KnownPeoplePackagePayload.Person] = []
        var editorPeople: [String: KnownPeoplePackageEditorPayload.PersonMetadata] = [:]
        var editorExamples: [String: KnownPeoplePackageEditorPayload.ExampleMetadata] = [:]
        let sorted = people.map { person in
            var value = person; value.embeddings.sort { $0.id.uuidString < $1.id.uuidString }; return value
        }
        for person in sorted {
            var examples: [KnownPeoplePackagePayload.Example] = []
            for example in person.embeddings {
                let key = example.id.uuidString.lowercased(), path = "embeddings/\(key).fem2", thumbnail = "embedding_thumbnails/\(key).jpg"
                files[path] = example.featurePrintData
                examples.append(try .init(id: example.id, embeddingPath: path, thumbnailPath: thumbnails[thumbnail] == nil ? nil : thumbnail))
                let mode: KnownPeoplePackageEditorPayload.RecognitionMode?
                switch example.recognitionMode {
                case .visionFeaturePrint: mode = .vision
                case .faceAndClothing: mode = .faceClothing
                case nil: mode = nil
                }
                editorExamples[key] = try .init(sourceDescription: example.sourceDescription,
                    addedAt: example.addedAt.timeIntervalSinceReferenceDate, recognitionMode: mode)
            }
            let key = person.id.uuidString.lowercased(), thumbnail = "thumbnails/\(key).jpg"
            corePeople.append(try .init(id: person.id, name: person.name, examples: examples,
                                       thumbnailPath: thumbnails[thumbnail] == nil ? nil : thumbnail))
            editorPeople[key] = try .init(role: person.role, notes: person.notes,
                representativeThumbnailID: person.representativeThumbnailID,
                createdAt: person.createdAt.timeIntervalSinceReferenceDate, updatedAt: person.updatedAt.timeIntervalSinceReferenceDate)
        }
        let payload = try KnownPeoplePackagePayload(people: corePeople)
        files["people.json"] = try encode(payload)
        func declarations() throws -> [KnownPeoplePackageManifest.FileDeclaration] {
            try files.keys.sorted().map { try .init(path: $0, byteCount: files[$0]!.count, sha256: hash(files[$0]!)) }
        }
        let embeddingCount = sorted.reduce(0) { $0 + $1.embeddings.count }
        let core = try KnownPeoplePackageManifest(libraryID: libraryID, exportedAt: exportedAt, exporter: exporter,
            peopleCount: sorted.count, embeddingCount: embeddingCount, files: declarations())
        let editor = try KnownPeoplePackageEditorPayload(libraryID: libraryID, coreRevision: core.coreRevision,
                                                        people: editorPeople, examples: editorExamples)
        let editorBytes = try encode(editor)
        files[KnownPeoplePackageManifest.EditorPayloadDescriptor.filePath] = editorBytes
        let descriptor = try KnownPeoplePackageManifest.EditorPayloadDescriptor(byteCount: editorBytes.count, sha256: hash(editorBytes))
        let manifest = try KnownPeoplePackageManifest(libraryID: libraryID, exportedAt: exportedAt, exporter: exporter,
            peopleCount: sorted.count, embeddingCount: embeddingCount, files: declarations(), editorPayload: descriptor)
        files["manifest.json"] = try encode(manifest)
        return .init(sourceDirectoryURL: root.url, sourceDevice: root.identity.st_dev, sourceInode: root.identity.st_ino,
                     manifest: manifest, payload: payload, editor: editor, files: files, people: sorted)
    }

    private static func canonicalPeople(_ people: [KnownPerson]) throws -> Data {
        try encode(people.sorted { $0.id.uuidString < $1.id.uuidString }.map { person in
            var result = person; result.embeddings.sort { $0.id.uuidString < $1.id.uuidString }; return result
        })
    }
    /// Mirrors the managed replacement's durable projection digest, including its directory
    /// domain separators and exact canonical local record encoding. The state hash binds the
    /// preserved package to its original installation, not to later intentional local edits.
    static func admittedProjectionHash(_ admitted: KnownPeoplePackageSnapshot) throws -> String {
        var projectionFiles: [String: Data] = [:]
        // Local service paths use UUID.uuidString, including on case-sensitive volumes.
        // The admitted package's lowercase names remain unchanged in its raw byte map.
        for person in admitted.people {
            projectionFiles["people/\(person.id.uuidString).json"] = try encode(person)
        }
        for person in admitted.payload.people {
            if let path = person.thumbnailPath {
                guard let bytes = admitted.files[path] else { throw KnownPeopleLocalStoreSnapshotFailure.invalidStateBinding }
                projectionFiles["thumbnails/\(person.id.uuidString).jpg"] = bytes
            }
            for example in person.examples {
                if let path = example.thumbnailPath {
                    guard let bytes = admitted.files[path] else { throw KnownPeopleLocalStoreSnapshotFailure.invalidStateBinding }
                    projectionFiles["embedding_thumbnails/\(example.id.uuidString).jpg"] = bytes
                }
            }
        }
        return try managedProjectionHash(files: projectionFiles, directories: ["people", "thumbnails", "embedding_thumbnails"])
    }
    private static func managedProjectionHash(files: [String: Data], directories: Set<String>) throws -> String {
        var hasher = SHA256()
        for directory in ["people", "thumbnails", "embedding_thumbnails"] {
            guard directories.contains(directory) else { throw KnownPeopleLocalStoreSnapshotFailure.invalidStateBinding }
            let relative = Dictionary(uniqueKeysWithValues: files.compactMap { path, bytes in
                path.hasPrefix(directory + "/") ? (String(path.dropFirst(directory.count + 1)), bytes) : nil
            })
            hasher.update(data: Data((directory + "/\0").utf8))
            for path in relative.keys.sorted() {
                hasher.update(data: Data(path.utf8)); hasher.update(data: Data([0]))
                hasher.update(data: relative[path]!); hasher.update(data: Data([0]))
            }
        }
        return hasher.finalize().map { String(format: "%02x", $0) }.joined()
    }
    private static func encode<T: Encodable>(_ value: T) throws -> Data {
        let encoder = JSONEncoder(); encoder.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
        return try encoder.encode(value)
    }
    private static func hash(_ bytes: Data) -> String { SHA256.hash(data: bytes).map { String(format: "%02x", $0) }.joined() }
    private static func localID(_ name: String, suffix: String) -> UUID? {
        guard name.hasSuffix(suffix) else { return nil }
        let text = String(name.dropLast(suffix.count))
        guard let id = UUID(uuidString: text), id.uuidString == text else { return nil }
        return id
    }
    private static func keys(_ object: [String: Any], required: Set<String>, optional: Set<String> = []) throws {
        let keys = Set(object.keys)
        guard required.isSubset(of: keys), keys.isSubset(of: required.union(optional)) else { throw KnownPeopleLocalStoreSnapshotFailure.invalidPerson }
    }
}

/// Retains the root descriptor across asynchronous package admission and validates all root
/// names/bytes twice. No directory enumeration, symlink traversal or migration is delegated to UI.
nonisolated private final class LocalRoot: @unchecked Sendable {
    struct Contents: Equatable {
        var files: [String: Data] = [:]
        var directories: Set<String> = []
        var managedInventorySHA256: String {
            var entries = files
            for directory in directories { entries[directory + "/"] = Data("directory".utf8) }
            return KnownPeopleManagedStoreInventoryToken.hash(entries: entries)
        }
    }
    let fd: Int32
    let identity: stat
    let url: URL
    deinit { close(fd) }
    init(_ url: URL, afterOpen: @Sendable () throws -> Void) throws {
        guard url.isFileURL, !url.path.contains("\0") else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeRoot }
        // Normalize only lexical separators/dot components. Resolving symlinks after open
        // could bless a replacement symlink pointing to the renamed original directory.
        // Parent traversal is refused instead of interpreting it through a possible symlink.
        let parts = url.path.split(separator: "/")
        guard url.path.hasPrefix("/"), !parts.contains("..") else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeRoot }
        let lexicalPath = "/" + parts.filter { $0 != "." }.joined(separator: "/")
        let descriptor = open(lexicalPath, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
        guard descriptor >= 0 else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeRoot }
        var adopted = false
        defer { if !adopted { close(descriptor) } }
        var identity = stat()
        guard fstat(descriptor, &identity) == 0 else { throw KnownPeopleLocalStoreSnapshotFailure.io }
        try afterOpen()
        var current = stat()
        guard lstat(lexicalPath, &current) == 0, current.st_mode & S_IFMT == S_IFDIR,
              current.st_dev == identity.st_dev, current.st_ino == identity.st_ino else {
            throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture
        }
        fd = descriptor; self.identity = identity
        self.url = URL(fileURLWithPath: lexicalPath, isDirectory: true)
        adopted = true
    }
    func verifyPath() throws {
        var info = stat()
        guard lstat(url.path, &info) == 0, info.st_mode & S_IFMT == S_IFDIR,
              info.st_dev == identity.st_dev, info.st_ino == identity.st_ino else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
    }
    func capture() throws -> Contents {
        var contents = Contents(), totalBytes = 0
        try walk(fd, prefix: "", contents: &contents, totalBytes: &totalBytes)
        return contents
    }
    private func walk(_ directory: Int32, prefix: String, contents: inout Contents, totalBytes: inout Int) throws {
        let copy = dup(directory)
        guard copy >= 0 else { throw KnownPeopleLocalStoreSnapshotFailure.io }
        guard let stream = fdopendir(copy) else { close(copy); throw KnownPeopleLocalStoreSnapshotFailure.io }
        defer { closedir(stream) }; rewinddir(stream)
        while true {
            try Task.checkCancellation()
            errno = 0
            guard let entry = readdir(stream) else {
                guard errno == 0 else { throw KnownPeopleLocalStoreSnapshotFailure.io }; break
            }
            let name = withUnsafePointer(to: &entry.pointee.d_name) {
                $0.withMemoryRebound(to: CChar.self, capacity: Int(NAME_MAX) + 1) { String(validatingCString: $0) }
            }
            guard let name else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeFile }
            if name == "." || name == ".." { continue }
            let path = prefix + name
            if path.hasPrefix("people/"), name.hasSuffix(".deleted") { throw KnownPeopleLocalStoreSnapshotFailure.tombstonesPresent }
            var info = stat()
            guard fstatat(directory, name, &info, AT_SYMLINK_NOFOLLOW) == 0 else { throw KnownPeopleLocalStoreSnapshotFailure.io }
            if info.st_mode & S_IFMT == S_IFDIR {
                let allowed = ["people", "thumbnails", "embedding_thumbnails", ".admitted-package",
                               ".admitted-package/editor", ".admitted-package/embeddings",
                               ".admitted-package/thumbnails", ".admitted-package/embedding_thumbnails"]
                guard allowed.contains(path) else { throw KnownPeopleLocalStoreSnapshotFailure.unsupportedRootEntry }
                let child = openat(directory, name, O_RDONLY | O_DIRECTORY | O_NOFOLLOW)
                guard child >= 0 else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeFile }
                defer { close(child) }
                var opened = stat()
                guard fstat(child, &opened) == 0, opened.st_dev == info.st_dev, opened.st_ino == info.st_ino else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
                contents.directories.insert(path)
                try walk(child, prefix: path + "/", contents: &contents, totalBytes: &totalBytes)
            } else {
                guard !prefix.isEmpty || name == KnownPeopleManagedStoreState.fileName else { throw KnownPeopleLocalStoreSnapshotFailure.unsupportedRootEntry }
                guard info.st_mode & S_IFMT == S_IFREG, info.st_nlink == 1,
                      info.st_size >= 0, info.st_size <= KnownPeoplePackageManifest.Limits().maximumFileBytes else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeFile }
                totalBytes += Int(info.st_size)
                guard totalBytes <= 1_500_000_000, contents.files.count < 410_010 else { throw KnownPeopleLocalStoreSnapshotFailure.sizeLimit }
                let file = openat(directory, name, O_RDONLY | O_NOFOLLOW | O_NONBLOCK)
                guard file >= 0 else { throw KnownPeopleLocalStoreSnapshotFailure.unsafeFile }
                defer { close(file) }
                var opened = stat()
                guard fstat(file, &opened) == 0, Self.same(info, opened) else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
                var bytes = Data(count: Int(info.st_size))
                try bytes.withUnsafeMutableBytes { buffer in
                    var offset = 0
                    while offset < buffer.count {
                        try Task.checkCancellation()
                        let amount = pread(file, buffer.baseAddress!.advanced(by: offset), min(65_536, buffer.count - offset), off_t(offset))
                        if amount < 0, errno == EINTR { continue }
                        guard amount > 0 else { throw KnownPeopleLocalStoreSnapshotFailure.io }
                        offset += amount
                    }
                }
                var after = stat()
                guard fstat(file, &after) == 0, Self.same(info, after) else { throw KnownPeopleLocalStoreSnapshotFailure.changedDuringCapture }
                contents.files[path] = bytes
            }
        }
    }
    private static func same(_ a: stat, _ b: stat) -> Bool {
        a.st_dev == b.st_dev && a.st_ino == b.st_ino && a.st_size == b.st_size && b.st_nlink == 1 &&
        a.st_mtimespec.tv_sec == b.st_mtimespec.tv_sec && a.st_mtimespec.tv_nsec == b.st_mtimespec.tv_nsec &&
        a.st_ctimespec.tv_sec == b.st_ctimespec.tv_sec && a.st_ctimespec.tv_nsec == b.st_ctimespec.tv_nsec
    }
}
